language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
node_js:
  - '7'
  - '6'
  - '4'
before_script:
  - npm prune
script:
  - npm run cover
  - npm run build
after_success:
  - npm run cover:report
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
